### ISSUE TITLE
Can't read compass data

### ISSUE THREAD

**Issue by bborncr** [KittenBot/pxt-nanobit#1]
Trying to read compass data using Input --> Compass Heading causes the Nanobit to freeze.

Reading the accelerometer and temperature data works just fine.

**Comment by xmeow** [comment]
since the usage of compass needs calibration, and the calibration needs 5x5 matrix, and we have removed the led matrix in favor of an oled screen. For now there is no obvious way of calibrate the magnetic sensor

**Comment by bborncr** [comment]
I got it working by doing the calibration blind. Thanks for the info!
